Post issue when IDs are malformed

diff --git a/.github/workflows/chebi.yml b/.github/workflows/chebi.yml
--- a/.github/workflows/chebi.yml
+++ b/.github/workflows/chebi.yml
@@ -131,7 +131,7 @@ jobs:
               echo "Failed preprocessing of ChEBI data."
               echo "FAILED=true" >> $GITHUB_ENV
           fi
-      - name: Diff versions
+      - name: RegEx and Diff test
         if:
           ${{ env.FAILED == 'false' }}
         run: |
@@ -155,7 +155,8 @@ jobs:
           else
             echo "Error: At least one line in the primary column does not match pattern."
             grep -nvE "^$CHEBI_ID$" "column1.txt"
-            #exit 1
+            echo "FAILED=true" >> $GITHUB_ENV
+            exit 1
           fi
 
           # Use grep to check if any line in the secondary column doesn't match the pattern
@@ -165,6 +166,7 @@ jobs:
           else
             echo "Error: At least one line in the secondary column does not match pattern."
             grep -nqvE "$CHEBI_ID" "column2.txt"
+            echo "FAILED=true" >> $GITHUB_ENV
             exit 1
           fi
           # sort them
diff --git a/.github/workflows/hmdb.yml b/.github/workflows/hmdb.yml
--- a/.github/workflows/hmdb.yml
+++ b/.github/workflows/hmdb.yml
@@ -137,7 +137,8 @@ jobs:
           else
             echo "Error: At least one line in the primary column does not match pattern."
             grep -nvE "^$HMDB_ID$" "column1.txt"
-            #exit 1
+            echo "FAILED=true" >> $GITHUB_ENV
+            exit 1
           fi
                   
           # Use grep to check if any line in the secondary column doesn't match the pattern
@@ -147,6 +148,7 @@ jobs:
           else
             echo "Error: At least one line in the secondary column does not match pattern."
             grep -nqvE "$HMDB_ID" "column2.txt"
+            echo "FAILED=true" >> $GITHUB_ENV
             exit 1
           fi
           # sort them
diff --git a/.github/workflows/ncbi.yml b/.github/workflows/ncbi.yml
--- a/.github/workflows/ncbi.yml
+++ b/.github/workflows/ncbi.yml
@@ -89,7 +89,7 @@ jobs:
               echo "FAILED=true" >> $GITHUB_ENV
           fi
       # step 4: compare the new and old data 
-      - name: Diff versions
+      - name: RegEx and Diff test
         if:
           ${{ env.FAILED == 'false' }}
         run: |
@@ -118,7 +118,8 @@ jobs:
           else
             echo "Error: At least one line in the primary column does not match pattern."
             grep -nvE "^$NCBI_ID$" "column1.txt"
-            #exit 1
+            echo "FAILED=true" >> $GITHUB_ENV
+            exit 1
           fi
                   
           # Use grep to check if any line in the secondary column doesn't match the pattern
@@ -128,6 +129,7 @@ jobs:
           else
             echo "Error: At least one line in the secondary column does not match pattern."
             grep -nqvE "$NCBI_ID" "column2.txt"
+            echo "FAILED=true" >> $GITHUB_ENV
             exit 1
           fi
           # sort them
