Added qc for new release identifiers

diff --git a/.github/workflows/chebi.yml b/.github/workflows/chebi.yml
--- a/.github/workflows/chebi.yml
+++ b/.github/workflows/chebi.yml
@@ -139,8 +139,21 @@ jobs:
           . datasources/chebi/config .
           old="datasources/chebi/data/$to_check_from_zenodo"
           new="datasources/chebi/recentData/$to_check_from_zenodo"
-          column_name="secondaryID"
-          # Extract the secondaryID column from both files and sort them
+          # remove headers
+          sed -i '1d' "$new"
+          sed -i '1d' "$old"
+          # qc integrity of IDs
+          wget -nc https://raw.githubusercontent.com/bridgedb/datasources/main/datasources.tsv
+          CHEBI_ID=$(awk -F '\t' '$1 == "ChEBI" {print $10}' datasources.tsv)
+          # Use grep to check if any line doesn't match the pattern
+          if ! grep -qvE "$CHEBI_ID" "$new"; then
+            echo "All lines match the pattern."
+            exit 0
+          else
+            echo "Error: At least one line does not match pattern."
+            exit 1
+          fi
+          # sort them
           cat "$old" | sort | tr -d "\r" > ids_old.txt
           cat "$new" | sort | tr -d "\r" > ids_new.txt
           echo "Performing diff between the sorted lists of IDs"
diff --git a/.github/workflows/hmdb.yml b/.github/workflows/hmdb.yml
--- a/.github/workflows/hmdb.yml
+++ b/.github/workflows/hmdb.yml
@@ -121,8 +121,21 @@ jobs:
           to_check_from_zenodo=$(grep -E '^to_check_from_zenodo=' datasources/hmdb/config | cut -d'=' -f2)
           old="datasources/hmdb/data/$to_check_from_zenodo"
           new="datasources/hmdb/recentData/$to_check_from_zenodo"
-          
-          # Extract the primarySymbol and secondarySymbol column from both files and sort them
+          # remove headers
+          sed -i '1d' "$new"
+          sed -i '1d' "$old"
+          # qc integrity of IDs
+          wget -nc https://raw.githubusercontent.com/bridgedb/datasources/main/datasources.tsv
+          HMDB_ID=$(awk -F '\t' '$1 == "HMDB" {print $10}' datasources.tsv)
+          # Use grep to check if any line doesn't match the pattern
+          if ! grep -qvE "$HMDB_ID" "$new"; then
+            echo "All lines match the pattern."
+            exit 0
+          else
+            echo "Error: At least one line does not match pattern."
+            exit 1
+          fi
+          # sort them
           cat "$old" | sort | tr -d "\r" > ids_old.txt
           cat "$new" | sort | tr -d "\r" > ids_new.txt
 
diff --git a/.github/workflows/ncbi.yml b/.github/workflows/ncbi.yml
--- a/.github/workflows/ncbi.yml
+++ b/.github/workflows/ncbi.yml
@@ -102,12 +102,25 @@ jobs:
 
           # Unzip the zip file 
           unzip datasources/ncbi/data/NCBI_secID2priID.zip -d datasources/ncbi/data/
-          # Extract the primaryID and secondaryID column from both files and sort them
+          # remove headers
+          sed -i '1d' "$new"
+          sed -i '1d' "$old"
+          # qc integrity of IDs
+          wget -nc https://raw.githubusercontent.com/bridgedb/datasources/main/datasources.tsv
+          NCBI_ID=$(awk -F '\t' '$1 == "Entrez Gene" {print $10}' datasources.tsv)
+          # Use grep to check if any line doesn't match the pattern
+          if ! grep -qvE "$NCBI_ID" "$new"; then
+            echo "All lines match the pattern."
+            exit 0
+          else
+            echo "Error: At least one line does not match pattern."
+            exit 1
+          fi
+          # sort them
           cat "$old" | sort | tr -d "\r" | cut -f 1,3 > ids_old.txt
           cat "$new" | sort | tr -d "\r" | cut -f 1,3 > ids_new.txt
 
           # TODO decide whether to perform diff on symbols too? 
-          # Extract the secondarySymbol column from both files and sort them
           ##cat "$old" | sort | tr -d "\r" | cut -f 4 > symbols_old.txt
           ##cat "$new" | sort | tr -d "\r" | cut -f 4 > symbols_new.txt
 
