Update hgnc.yml

diff --git a/.github/workflows/hgnc.yml b/.github/workflows/hgnc.yml
--- a/.github/workflows/hgnc.yml
+++ b/.github/workflows/hgnc.yml
@@ -68,13 +68,36 @@ jobs:
           echo "$DATE_NEW=$DATE_NEW" >> $GITHUB_ENV
           echo "$COMPLETE_NEW=$COMPLETE_NEW" >> $GITHUB_ENV
           echo "$WITHDRAWN_NEW=$WITHDRAWN_NEW" >> $GITHUB_ENV
-          
           ##Create temp. folder to store the data in
           mkdir -p datasources/hgnc/data
           ##Download hgnc file
           wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/${WITHDRAWN_NEW}
           wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/${COMPLETE_NEW}
-          ls -trlh
           mv $WITHDRAWN_NEW $COMPLETE_NEW datasources/hgnc/data
           ##Check file size if available
           ls -trlh datasources/hgnc/data
+      # step 3: run the Rscripts for hgnc preprocessing 
+      - name: Install R
+        uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: '4.1' # Specify the R version
+          include-recommended: true      
+      - name: Test hgnc data processing
+        id: hgnc_process
+        run: |
+          sourceVersion=$DATE_NEW
+          complete="datasources/hgnc/data/${COMPLETE_NEW}" 
+          withdrawn="datasources/hgnc/data/${WITHDRAWN_NEW}" 
+
+          # Run rscripts program and capture its exit code
+          Rscript r/src/hgnc.R $sourceVersion $withdrawn $complete
+          # Check the exit status of the R script
+          if [ $? -eq 0 ]; then
+              # script succeeded
+              echo "Successful preprocessing of hgnc data."
+              echo "FAILED=false" >> $GITHUB_ENV
+          else
+              # script failed
+              echo "Failed preprocessing of hgnc data."
+              echo "FAILED=true" >> $GITHUB_ENV
+          fi
