Update ncbi.yml

diff --git a/.github/workflows/ncbi.yml b/.github/workflows/ncbi.yml
--- a/.github/workflows/ncbi.yml
+++ b/.github/workflows/ncbi.yml
@@ -77,12 +77,16 @@ jobs:
         run: |
           # Set up vars from config file
           sourceVersion=$DATE_NEW
-          gene_history="data/gene_history.gz" 
-          gene_info="data/gene_info.gz" 
+          gene_history="datasources/ncbi/data/gene_history.gz"
+          gene_info="datasources/ncbi/data/gene_info.gz"
           outputDir="datasources/ncbi/recentData/"
           mkdir -p "$outputDir"
           # Run Java program and capture its exit code
-          java -cp java/target/mapping_prerocessing-0.0.1-jar-with-dependencies.jar org.sec2pri.ncbi_txt $sourceVersion $gene_history $gene_info $outputDir
+          java -cp java/target/mapping_prerocessing-0.0.1-jar-with-dependencies.jar \
+              org.sec2pri.ncbi_txt "$sourceVersion" "$gene_history" "$gene_info" "$outputDir"
+          
+              ls -lh "$outputDir" || echo "Output directory missing"
+          ls -lh "$outputDir/NCBI_secID2priID.tsv" || echo "Output file missing"
           # Check the exit status of the Java program
           if [ $? -eq 0 ]; then
               # Java program succeeded
@@ -108,7 +112,7 @@ jobs:
           # Unzip the zip file 
           unzip -l datasources/ncbi/data/NCBI_secID2priID.zip
 
-          unzip datasources/ncbi/data/NCBI_secID2priID.zip -d datasources/ncbi/data/
+          unzip datasources/ncbi/data/NCBI_secID2priID.zip -d datasources/ncbi/recentData/
           # remove headers
           sed -i '1d' "$new"
           sed -i '1d' "$old"
