ncbi_debug (#174)
* Update ncbi.yml

* Update ncbi.R

* Update ncbi.R

* Update ncbi.R

* Update ncbi.yml

* Create ncbi_txt.java

* R to java

Implemented until
# Read the file that includes the gene info

* Update ncbi_txt.java

* Update uniprot.R

* Revert "Update uniprot.R"

This reverts commit 8ceb351185dc2208896e57115c83d3a03846f914.

* Update ncbi_txt.java

* update jar

* Update ncbi.yml

* Update ncbi.R

* Update ncbi.R

* Update ncbi.R

* Update config

* Update ncbi.yml

* Update ncbi.yml

* Update ncbi.yml

* Update ncbi.yml

* Update ncbi_txt.java

* Update ncbi.yml

* Update ncbi.yml

* Update ncbi.yml

* Update ncbi.yml

diff --git a/.github/workflows/ncbi.yml b/.github/workflows/ncbi.yml
--- a/.github/workflows/ncbi.yml
+++ b/.github/workflows/ncbi.yml
@@ -63,33 +63,42 @@ jobs:
           mv gene_info.gz gene_history.gz datasources/ncbi/data
           ##Check file size if available
           ls -trlh datasources/ncbi/data
-      # step 3: run the Rscripts for ncbi preprocessing 
-      - name: Install R
-        uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: '4.1' # Specify the R version
-          include-recommended: true      
-      - name: Test ncbi data processing
-        id: ncbi_process
-        run: |
-          sourceVersion=$DATE_NEW
-          gene_history="data/gene_history.gz" 
-          gene_info="data/gene_info.gz" 
 
-          # Run rscripts program and capture its exit code
-          Rscript r/src/ncbi.R $sourceVersion $gene_history $gene_info
-          # Check the exit status of the R script
+          
+      # step 3: run the jar for ncbi preprocessing 
+      - name: Set up Java
+        uses: actions/setup-java@v4
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+          
+      - name: Test ncbi txt data processing
+        id: txt_process
+        run: |
+          # Set up vars from config file
+          sourceVersion=$DATE_NEW
+          gene_history="datasources/ncbi/data/gene_history.gz"
+          gene_info="datasources/ncbi/data/gene_info.gz"
+          outputDir="datasources/ncbi/recentData/"
+          mkdir -p "$outputDir"
+          # Run Java program and capture its exit code
+          java -cp java/target/mapping_prerocessing-0.0.1-jar-with-dependencies.jar \
+              org.sec2pri.ncbi_txt "$sourceVersion" "$gene_history" "$gene_info" "$outputDir"
+          
+              ls -lh "$outputDir" || echo "Output directory missing"
+          ls -lh "$outputDir/NCBI_secID2priID.tsv" || echo "Output file missing"
+          # Check the exit status of the Java program
           if [ $? -eq 0 ]; then
-              # script succeeded
-              echo "Successful preprocessing of ncbi data."
+              # Java program succeeded
+              echo "Successful preprocessing of NCBI data."
               echo "FAILED=false" >> $GITHUB_ENV
           else
               # script failed
-              echo "Failed preprocessing of ncbi data."
+              echo "Failed preprocessing of NCBI data."
               echo "FAILED=true" >> $GITHUB_ENV
           fi
       # step 4: compare the new and old data 
-      - name: RegEx and Diff test
+      - name: Diff versions
         if:
           ${{ env.FAILED == 'false' }}
         run: |
@@ -101,16 +110,18 @@ jobs:
           echo $column_name
 
           # Unzip the zip file 
-          unzip datasources/ncbi/data/NCBI_secID2priID.zip -d datasources/ncbi/data/
+          unzip -o datasources/ncbi/data/NCBI_secID2priID.zip -d datasources/ncbi/data/
           # remove headers
-          sed -i '1d' "$new"
-          sed -i '1d' "$old"
+          cp "$new" new_tmp.tsv
+          cp "$old" old_tmp.tsv
+          sed -i '1d' new_tmp.tsv
+          sed -i '1d' old_tmp.tsv
           # qc integrity of IDs
           wget -nc https://raw.githubusercontent.com/bridgedb/datasources/main/datasources.tsv
           NCBI_ID=$(awk -F '\t' '$1 == "Entrez Gene" {print $10}' datasources.tsv)
           # Split the file into two separate files for each column
-          awk -F '\t' '{print $1}' $new > column1.txt
-          awk -F '\t' '{print $2}' $new > column2.txt
+          awk -F '\t' '{print $1}' new_tmp.tsv > column1.txt
+          awk -F '\t' '{print $2}' new_tmp.tsv > column2.txt
                   
           # Use grep to check if any line in the primary column doesn't match the pattern
           if grep -nqvE "$NCBI_ID" "column1.txt"; then
@@ -133,12 +144,12 @@ jobs:
             exit 1
           fi
           # sort them
-          cat "$old" | sort | tr -d "\r" | cut -f 1,3 > ids_old.txt
-          cat "$new" | sort | tr -d "\r" | cut -f 1,3 > ids_new.txt
+          cat old_tmp.tsv | sort | tr -d "\r" | cut -f 1,3 > ids_old.txt
+          cat new_tmp.tsv | sort | tr -d "\r" | cut -f 1,3 > ids_new.txt
 
           # TODO decide whether to perform diff on symbols too? 
-          ##cat "$old" | sort | tr -d "\r" | cut -f 4 > symbols_old.txt
-          ##cat "$new" | sort | tr -d "\r" | cut -f 4 > symbols_new.txt
+          ##cat old_tmp.tsv | sort | tr -d "\r" | cut -f 4 > symbols_old.txt
+          ##cat new_tmp.tsv | sort | tr -d "\r" | cut -f 4 > symbols_new.txt
 
           echo "Performing diff between the sorted lists of IDs"
 
