Test columns separately

diff --git a/.github/workflows/ncbi.yml b/.github/workflows/ncbi.yml
--- a/.github/workflows/ncbi.yml
+++ b/.github/workflows/ncbi.yml
@@ -108,13 +108,26 @@ jobs:
           # qc integrity of IDs
           wget -nc https://raw.githubusercontent.com/bridgedb/datasources/main/datasources.tsv
           NCBI_ID=$(awk -F '\t' '$1 == "Entrez Gene" {print $10}' datasources.tsv)
-          # Use grep to check if any line doesn't match the pattern
-          if ! grep -qvE "$NCBI_ID" "$new"; then
-            echo "All lines match the pattern."
+          # Split the file into two separate files for each column
+          awk -F '\t' '{print $1}' $new > column1.txt
+          awk -F '\t' '{print $2}' $new > column2.txt
+                  
+          # Use grep to check if any line in the primary column doesn't match the pattern
+          if grep -nqvE "$NCBI_ID" "column1.txt"; then
+            echo "All lines in the primary column match the pattern."
+          else
+            echo "Error: At least one line in the primary column does not match pattern."
+            grep -nvE "^$NCBI_ID$" "column1.txt"
+            #exit 1
+          fi
+                  
+          # Use grep to check if any line in the secondary column doesn't match the pattern
+          if grep -nqvE "$NCBI_ID" "column1.txt"; then
+            echo "All lines in the secondary column match the pattern."
             exit 0
           else
-            echo "Error: At least one line does not match pattern."
-            grep -vnE "$NCBI_ID" "$new" | sed 's/:.*//'
+            echo "Error: At least one line in the secondary column does not match pattern."
+            grep -nqvE "$NCBI_ID" "column2.txt"
             exit 1
           fi
           # sort them
