Update wikidata.yml
Checking for timeout in query results

diff --git a/.github/workflows/wikidata.yml b/.github/workflows/wikidata.yml
--- a/.github/workflows/wikidata.yml
+++ b/.github/workflows/wikidata.yml
@@ -19,23 +19,31 @@ jobs:
       - name: Run the Queries
         run: |
           ## Download outdated IDs for chemicals
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/metabolites_secID2priID.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/metabolites_secID2priID.tsv
           ## Download all primary IDs for chemicals
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/metabolites_priIDs.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/metabolites_priIDs.tsv
           ## Download alias/synonyms/names for chemicals
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalPrimarySynonyms.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/metabolites_name2synonym.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/chemicalPrimarySynonyms.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/metabolites_name2synonym.tsv
           
           ## Download outdated IDs for genes and proteins
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/geneProtein_secID2priID.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/geneProtein_secID2priID.tsv
           ## Download all primary IDs for genes and proteins
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/geneProtein_priIDs.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/geneProtein_priIDs.tsv
           ## Download alias/synonyms/names for genes and proteins
-          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanPrimarySynonyms.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/geneProtein_name2synonym.tsv
+          curl -H "Accept: text/tab-separated-values" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanPrimarySynonyms.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/results/geneProtein_name2synonym.tsv
+
+          ##Check new data, fail job if query timeout has occured
+          cd datasources/Wikidata/results
+          for File in *.tsv ##Only for tsv files
+          if grep -q TimeoutException "$File"; then
+            exit 1
+          fi
+          cd ..
           
-          ##Remove Wikidata IRIs
-          cd datasources/Wikidata/data
-          ##Remove previous output files
-          find  . -name 'Wikidata*' -exec rm {} \;
+          ##Remove Wikidata IRIs in query results
+          cd results
+          ##Remove previous output files (if existing)
+          ##find  . -name 'Wikidata*' -exec rm {} \;
           ## Set prefix to Wikidata for renaming new data files
           prefix=$(basename "Wikidata") 
           for f in *.tsv ##Only for tsv files
@@ -44,7 +52,10 @@ jobs:
             cat "$f" | sed 's/<http:\/\/www.wikidata.org\/entity\///g' | sed 's/[>]//g' | sed 's/@en//g' > "${prefix}_$f"
             rm "$f"
           done
+          ##Change back to main directory
           cd ../..
+          ##Move and overwrite all files from results folder to data folder, to update previous data
+          mv -f datasources/Wikidata/results/* datasources/Wikidata/data/
       # step 3: save the data from the queries
       - name: Commit and Push Changes
         run: |
